### ISSUE TITLE
upgrading to VS 2013

### ISSUE THREAD

**Issue by HarishNayak** [NModbus4/NModbus4#103]
NModbus setup...upgrading to VS 2013.  I am having issues with incompatible files Can someone help me?

**Comment by james9837** [comment]
You'll need to be more specific. What steps led to the problem, what files are 'incompatible'?

I have not run into issues building NModbus4 with Studio 2013.

**Comment by Maxwe11** [comment]
> upgrading to VS 2013

It sounds like downgrading :smile:
