### ISSUE TITLE
Question:How to query current connection status of a current  ModbusMaster object?

### ISSUE THREAD

**Issue by lzz42** [NModbus4/NModbus4#148]
Eg:I Had a ModBusMaster Object tranport what ever Serial or TCP/UDP，is there some way or some function to get this object connection state(Just read some Address ?) ? Maybe is very simple :)

**Comment by 61131** [comment]
@seainchina - There isn't any explicit method within the NModbus4 library that can be used to return the "state" of a Modbus master instance. For TCP connections however, the System.Net.Sockets.TcpClient object that is passed to the ModbusIpMaster.CreateIp method has a Connected attribute that can be queried directly to determine the TCP connection state.

I would note though that while this can be done for TCP connections associated with the Modbus master, the concept of "state" is less tangible with serial communications as there isn't a distinct "connection" that is formed between the master station and slave station - Rather, a request is simply transmitted by the Modbus master on the serial line - which depending upon the nature of the serial line may be multiplex in nature - and then awaits for the timeout period for a matching response.  There isn't any explicit connection formed or established to transmit or receive this data in the same manner that there is for a TCP connection between hosts.

**Comment by lzz42** [comment]
thanks for your answer!
