### ISSUE TITLE
Make NModbus4 portable

### ISSUE THREAD

**Issue by Maxwe11** [NModbus4/NModbus4#30]

**Comment by rquackenbush** [comment]
This is something that I'm very interested in. I'm currently working on porting some of my .NET / NModbus4 code over to Linux. I am available to test anything you come up with.

**Comment by Maxwe11** [comment]
@rquackenbush thanks. I think future target will be [dotnet](http://oren.codes/2015/06/09/pcls-net-core-dnx-and-uwp/) so #27 and #28 become unnecessary.
