### ISSUE TITLE
Error codes of failed requests

### ISSUE THREAD

**Issue by justfony** [NModbus4/NModbus4#72]
How to get an error code of failed requests? It is necessary for my project.

**Comment by justfony** [comment]
I can't find the way to get these codes in source code of framework..

**Comment by Maxwe11** [comment]
@FonyRockfeel could you clarify what error code do you need? 
If you mean modbus exception codes then `SlaveException`  and its  property `SlaveExceptionCode` is what you need.

**Comment by justfony** [comment]
I have this code:

```
    PortName = cfg.Port;

     _port = new SerialPort(PortName) {BaudRate = cfg.BaudRate, ReadTimeout = cfg.Timeout};

     _modbus = ModbusSerialMaster.CreateRtu(_port);

     _modbus.Transport.Retries = 3;
     _modbus.Transport.WaitToRetryMilliseconds = 250;
     var regs = _modbus.ReadHoldingRegisters(slave, start, amount).ToList();
```

How to use SlaveException class in this code?

**Comment by Maxwe11** [comment]
`ReadHoldingRegisters` throws `SlaveException` in case if your device returns modbus exception code

**Comment by justfony** [comment]
Thank you!
