### ISSUE TITLE
Holding registers do not change after writing in them!

### ISSUE THREAD

**Issue by disklosr** [NModbus4/NModbus4#78]
Create a slave modbus device.
Send a write command to write into one of the Holding Registers inside the slave
Read the written holding register
The read value is always zero

**Comment by Maxwe11** [comment]
@disklosr what version do you use?

**Comment by disklosr** [comment]
I used the lastest available beta version from nuget

**Comment by Maxwe11** [comment]
@disklosr could you share your code for repro?

**Comment by disklosr** [comment]
Turned out it actually writes starting from the next register.

So I issue a command to write value X in holding register 2274
After reading I print the content of register 2274 and the value is 0
But if I print the value of the register 2275 it prints the value X

Is this normal behavior? I am using the TCP implementation of modbus btw.

**Comment by Maxwe11** [comment]
Sorry for the delay. Yes it's normal behavior.

**Comment by Maxwe11** [comment]
@disklosr if you have any further comments about this feel free to reopen issue.

**Comment by disklosr** [comment]
Thanks I will.
I'm actually using your library to make a GUI modbus slave simulator for Windows. Keep up the good work!
