### ISSUE TITLE
Response code indication while using Modbus RTU

### ISSUE THREAD

**Issue by Ankita-XIT** [NModbus4/NModbus4#83]
I am using Modbus RTU protocol to read data. I have Slave Id = 1 and Modbus Address = 40023. I am configuring Start Address = 22. <b>Is it correct with my Modbus Address?</b>

If I am configuring following details:
Slave Id= 1
Baud Rate = 115200
Stop Bits = 2
Data Bits = 8
Parity = None
Start Address = 22
I am reading data with following code

<pre>
var master = ModbusSerialMaster.CreateRtu(port);
ushort[] registers = master.ReadHoldingRegisters(slaveId, startAddress, 2);  //2 is number of points
</pre>

With these details I am getting this response in console:
<b>INFO Modbus.IO.ModbusSerialTransport - TX: 1, 3, 0, 22, 0, 2, 37, 207</b>
In above response I only know some of them what they indicate like first digit 1 indicate Slave Id, 3 indicate function Code, 22 indicate Start Address, 2 indicate number of points.

Can anyone please explain me remaining code? What they indicate?

Thanks,
Ankita

**Comment by Maxwe11** [comment]
http://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b.pdf
