### ISSUE TITLE
Multiple slaves on the same COM port

### ISSUE THREAD

**Issue by justfony** [NModbus4/NModbus4#87]
Is it real to run multiple modbus slave devices on the same COM port?

**Comment by Maxwe11** [comment]
Yep, that's possible with current implementation but IIRC only one instance of `SerialPort` could be in open state. Why do you need multiple slaves?

**Comment by justfony** [comment]
Now I'm working on the industrial program, but i haven't access to equipment network. Therefore I need to emulate multiple slave devices to debug my project. Yes, only one instance of SerialPort could be in open state, but i think i have already found the solution.  Adding some modification to  ModbusSerialSlave class constructor and Listen() method will solve my problem.
