### ISSUE TITLE
Connecting as a modbus TCP/IP Client with specification of the node for the slave

### ISSUE THREAD

**Issue by MSUKPR** [NModbus4/NModbus4#91]
Hi, 

I haven't seen the option how I can connect to the network of modbus devices with one modbus TCP/IP <> RTU converter. 

I have one IP adress, but in order to get data from different devices I need to specify the nodeId of the slave. 

Any hint?

**Comment by Maxwe11** [comment]
If you want to use RTU over TCP/IP you shoud create `ModbusSerialMaster` with `TcpClient`.

**Comment by MSUKPR** [comment]
Thank you for your fast response. I will check this in a moment

Kind regards,

Mateusz Siatrak
Software Engineer
UK Power Reserve Ltd
Mobile: +44 7525 796501
Email: Mateusz.Siatrak@ukpowerreserve.com

**Comment by MSUKPR** [comment]
I have again question:

I've got code like that:

``` c#
using Modbus.Device;
using System;
using System.Net.Sockets;

namespace ModbusRTU_TCP
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            using (TcpClient client = new TcpClient("192.168.250.111", 502))
            {

                IModbusSerialMaster master = ModbusSerialMaster.CreateRtu(client);
                ushort[] test = master.ReadInputRegisters(1, 10, 10);

                Console.WriteLine(test)
                Console.ReadLine();
            }
        }
    }
}
```

But I am not able to get any data, and I'm not getting any errors. Am I missing something?

**Comment by Maxwe11** [comment]
1. try set timeout for `TcpClient`.
2. Are you sure that your slave also uses RTU?

**Comment by ravigyanvihar** [comment]
@Maxwe11
Sir 
I am facing the same issue can you tell me the above method is correct

**Comment by juspolo** [comment]
@Maxwe11 @ravigyanvihar @MSUKPR , for my experience you should use the ModbusIpMaster when using TCP, while you should use ModbusSerialMaster when using Serial :)

For example, if you are using an ethernet to 485 Modbus converter you could do something like this:
```
using (TcpClient client = new TcpClient(TargetConverterIP, TargetIPPort)    // e.g. 192.168.1.128 and 502.
{
    // create modbus master for TCP Modbus
    IModbusMaster master = ModbusIpMaster.CreateIp(client);
    ushort[] holding_register = master.ReadHoldingRegisters(slaveAddress, startAddress, numberOfRegisters);    // e.g. 1, 0, and 1.
}
```
I hope that it could help you, even if it is a bit late.

P.S. if your ethernet to 485 converter is transparent, then you should probably encapsulate your RTU modbus packets into TCP by:
```
using (TcpClient client = new TcpClient(TargetConverterIP, TargetIPPort)    // e.g. 192.168.1.127 and 4001.
{
    // create modbus master for RTU Modbus
    IModbusMaster master = ModbusSerialMaster.CreateRTU(client as TCPClient);
    ushort[] holding_register = master.ReadHoldingRegisters(slaveAddress, startAddress, numberOfRegisters);    // e.g. 1, 0, and 1.
}
```
